input:
  kafka:
    addresses:
      - ${KAFKA_HOST}
    topics:
      - ${KAFKA_PAYMENT_TOPIC}
    client_id: reconciliation
      enabled: ${KAFKA_TLS_ENABLED}
    sasl:
      enabled: ${KAFKA_SASL_ENABLED}
      mechanism: ${KAFKA_SASL_MECHANISM}
      user: ${KAFKA_USER_NAME}
      password: ${KAFKA_PASSWORD}
    consumer_group: ${KAFKA_CONSUMER_GROUP}

output:
  broker:
    outputs:
      - stdout: { }
      - mongodb:
          url: ${MONGODB_CONN_STRING}
          database: ${MONGODB_DATABASE_NAME}
          collection: ${MONGODB_PAYMENT_COLLECTION}
          operation: update-one
          upsert: true
          filter_map: root._id = meta("id")
          document_map: |
            root = {
              "$set": this
            }
          write_concern:
            w: 'majority'
            w_timeout: '5s'