// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AcceptAlertRequest - Business acceptance. `note` is required and the evidence is snapshotted onto the resolution.
type AcceptAlertRequest struct {
	// Who is accepting the break
	By string `json:"by"`
	// Why the break is being accepted rather than corrected
	Note string `json:"note"`
}

func (a *AcceptAlertRequest) GetBy() string {
	if a == nil {
		return ""
	}
	return a.By
}

func (a *AcceptAlertRequest) GetNote() string {
	if a == nil {
		return ""
	}
	return a.Note
}
