// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

// Ack - Record of who acknowledged an alert and when
type Ack struct {
	// Who acknowledged the alert
	By string `json:"by"`
	// When the alert was acknowledged
	At time.Time `json:"at"`
	// Free-text note left by whoever acknowledged the alert
	Note *string `json:"note,omitzero"`
}

func (a Ack) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Ack) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Ack) GetBy() string {
	if a == nil {
		return ""
	}
	return a.By
}

func (a *Ack) GetAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.At
}

func (a *Ack) GetNote() *string {
	if a == nil {
		return nil
	}
	return a.Note
}
