// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AckAlertRequest struct {
	// Who is acknowledging the alert
	By string `json:"by"`
	// Free-text note to record with the acknowledgement
	Note *string `json:"note,omitzero"`
}

func (a *AckAlertRequest) GetBy() string {
	if a == nil {
		return ""
	}
	return a.By
}

func (a *AckAlertRequest) GetNote() *string {
	if a == nil {
		return nil
	}
	return a.Note
}
