// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/optionalnullable"
	"time"
)

// Type - What happened, whether an evaluation outcome or a manual transition
type Type string

const (
	TypeFail     Type = "fail"
	TypePass     Type = "pass"
	TypeAck      Type = "ack"
	TypeResolve  Type = "resolve"
	TypeAccept   Type = "accept"
	TypeSnooze   Type = "snooze"
	TypeUnsnooze Type = "unsnooze"
)

func (e Type) ToPointer() *Type {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Type) IsExact() bool {
	if e != nil {
		switch *e {
		case "fail", "pass", "ack", "resolve", "accept", "snooze", "unsnooze":
			return true
		}
	}
	return false
}

// PrevStatus - Status before this event. Null only for the alert's inaugural event
type PrevStatus string

const (
	PrevStatusOpen         PrevStatus = "OPEN"
	PrevStatusAcknowledged PrevStatus = "ACKNOWLEDGED"
	PrevStatusResolved     PrevStatus = "RESOLVED"
)

func (e PrevStatus) ToPointer() *PrevStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PrevStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "OPEN", "ACKNOWLEDGED", "RESOLVED":
			return true
		}
	}
	return false
}

// NewStatus - Status after this event
type NewStatus string

const (
	NewStatusOpen         NewStatus = "OPEN"
	NewStatusAcknowledged NewStatus = "ACKNOWLEDGED"
	NewStatusResolved     NewStatus = "RESOLVED"
)

func (e NewStatus) ToPointer() *NewStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NewStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "OPEN", "ACKNOWLEDGED", "RESOLVED":
			return true
		}
	}
	return false
}

// AlertEvent - One row of the alert's append-only event log. Captures every
// evaluation that touched the alert plus every manual transition
// (ack / resolve / accept / snooze / unsnooze). `prevStatus` is null
// only for the inaugural event of an alert. `isReopen` is a derived
// predicate — true when a FAIL event lands on a previously-RESOLVED alert.
// `notify` is the notification decision recorded for the row: false marks
// a transition kept for audit but deliberately not published (a repeated
// identical fail, or a fail muted by an active snooze).
type AlertEvent struct {
	// Unique identifier of the event
	ID string `json:"id"`
	// Identifier of the alert this event belongs to
	AlertID string `json:"alertID"`
	// Identifier of the evaluation that produced this event, absent for manual transitions
	EvaluationID optionalnullable.OptionalNullable[string] `json:"evaluationID,omitzero"`
	// What happened, whether an evaluation outcome or a manual transition
	Type Type `json:"type"`
	// Status before this event. Null only for the alert's inaugural event
	PrevStatus optionalnullable.OptionalNullable[PrevStatus] `json:"prevStatus,omitzero"`
	// Status after this event
	NewStatus NewStatus `json:"newStatus"`
	// Event-type-specific payload (evidence for fail, resolution for resolve/accept, ack object for ack, snooze object for snooze).
	Payload map[string]any `json:"payload,omitzero"`
	// When the event occurred
	At time.Time `json:"at"`
	// True when a failure landed on an already-resolved alert, reopening it
	IsReopen bool `json:"isReopen"`
	// Whether this transition was published to the message bus. false = recorded for audit but suppressed.
	Notify bool `json:"notify"`
}

func (a AlertEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AlertEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AlertEvent) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AlertEvent) GetAlertID() string {
	if a == nil {
		return ""
	}
	return a.AlertID
}

func (a *AlertEvent) GetEvaluationID() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.EvaluationID
}

func (a *AlertEvent) GetType() Type {
	if a == nil {
		return Type("")
	}
	return a.Type
}

func (a *AlertEvent) GetPrevStatus() optionalnullable.OptionalNullable[PrevStatus] {
	if a == nil {
		return nil
	}
	return a.PrevStatus
}

func (a *AlertEvent) GetNewStatus() NewStatus {
	if a == nil {
		return NewStatus("")
	}
	return a.NewStatus
}

func (a *AlertEvent) GetPayload() map[string]any {
	if a == nil {
		return nil
	}
	return a.Payload
}

func (a *AlertEvent) GetAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.At
}

func (a *AlertEvent) GetIsReopen() bool {
	if a == nil {
		return false
	}
	return a.IsReopen
}

func (a *AlertEvent) GetNotify() bool {
	if a == nil {
		return false
	}
	return a.Notify
}
