// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AlertEventsCursorResponseCursor - Paginated cursor wrapping the alert's event log
type AlertEventsCursorResponseCursor struct {
	PageSize int64        `json:"pageSize"`
	HasMore  bool         `json:"hasMore"`
	Previous *string      `json:"previous,omitzero"`
	Next     *string      `json:"next,omitzero"`
	Data     []AlertEvent `json:"data"`
}

func (a *AlertEventsCursorResponseCursor) GetPageSize() int64 {
	if a == nil {
		return 0
	}
	return a.PageSize
}

func (a *AlertEventsCursorResponseCursor) GetHasMore() bool {
	if a == nil {
		return false
	}
	return a.HasMore
}

func (a *AlertEventsCursorResponseCursor) GetPrevious() *string {
	if a == nil {
		return nil
	}
	return a.Previous
}

func (a *AlertEventsCursorResponseCursor) GetNext() *string {
	if a == nil {
		return nil
	}
	return a.Next
}

func (a *AlertEventsCursorResponseCursor) GetData() []AlertEvent {
	if a == nil {
		return []AlertEvent{}
	}
	return a.Data
}

// AlertEventsCursorResponse - OK
type AlertEventsCursorResponse struct {
	// Paginated cursor wrapping the alert's event log
	Cursor AlertEventsCursorResponseCursor `json:"cursor"`
}

func (a *AlertEventsCursorResponse) GetCursor() AlertEventsCursorResponseCursor {
	if a == nil {
		return AlertEventsCursorResponseCursor{}
	}
	return a.Cursor
}
