// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AlertsCursorResponseCursor - Paginated cursor wrapping the list of alerts
type AlertsCursorResponseCursor struct {
	PageSize int64   `json:"pageSize"`
	HasMore  bool    `json:"hasMore"`
	Previous *string `json:"previous,omitzero"`
	Next     *string `json:"next,omitzero"`
	Data     []Alert `json:"data"`
}

func (a *AlertsCursorResponseCursor) GetPageSize() int64 {
	if a == nil {
		return 0
	}
	return a.PageSize
}

func (a *AlertsCursorResponseCursor) GetHasMore() bool {
	if a == nil {
		return false
	}
	return a.HasMore
}

func (a *AlertsCursorResponseCursor) GetPrevious() *string {
	if a == nil {
		return nil
	}
	return a.Previous
}

func (a *AlertsCursorResponseCursor) GetNext() *string {
	if a == nil {
		return nil
	}
	return a.Next
}

func (a *AlertsCursorResponseCursor) GetData() []Alert {
	if a == nil {
		return []Alert{}
	}
	return a.Data
}

// AlertsCursorResponse - OK
type AlertsCursorResponse struct {
	// Paginated cursor wrapping the list of alerts
	Cursor AlertsCursorResponseCursor `json:"cursor"`
}

func (a *AlertsCursorResponse) GetCursor() AlertsCursorResponseCursor {
	if a == nil {
		return AlertsCursorResponseCursor{}
	}
	return a.Cursor
}
