// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

// Status - Where the alert stands in its open, acknowledged, resolved lifecycle
type Status string

const (
	StatusOpen         Status = "OPEN"
	StatusAcknowledged Status = "ACKNOWLEDGED"
	StatusResolved     Status = "RESOLVED"
)

func (e Status) ToPointer() *Status {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Status) IsExact() bool {
	if e != nil {
		switch *e {
		case "OPEN", "ACKNOWLEDGED", "RESOLVED":
			return true
		}
	}
	return false
}

// An Alert is the stable, dedup'd record of a failing fingerprint within a
// reconciliation period. There is exactly one Alert per
// (ruleID, fingerprint, periodID) — within a period, re-opens after resolve
// flip the status back to OPEN in place; the same fingerprint failing in a
// new period is a separate Alert. For a `continuous`-cadence rule there is
// one unbounded period, so it behaves as one Alert per (ruleID, fingerprint).
// The full history of transitions lives in alert_event
// (see /alerts/{alertID}/events).
type Alert struct {
	// Unique identifier of the alert
	ID string `json:"id"`
	// Identifier of the rule that raised the alert
	RuleID string `json:"ruleID"`
	// Identifies what is failing within the rule, so the same break dedupes to one alert
	Fingerprint string `json:"fingerprint"`
	// Reconciliation period this alert is scoped to ('continuous' for live-monitoring rules).
	PeriodID string `json:"periodID"`
	// Where the alert stands in its open, acknowledged, resolved lifecycle
	Status Status `json:"status"`
	// How serious an alert is, used to route and prioritise notifications
	Severity Severity `json:"severity"`
	// When the fingerprint first failed within this period
	FirstSeenAt time.Time `json:"firstSeenAt"`
	// When the fingerprint most recently failed
	LastSeenAt time.Time `json:"lastSeenAt"`
	// Count of FAIL events on this alert across reopen cycles within its period (lifetime, for a continuous-cadence rule).
	OccurrenceCount int64 `json:"occurrenceCount"`
	// Identifier of the evaluation that last touched the alert
	LastEvaluationID string `json:"lastEvaluationID"`
	// Data captured from the failing evaluation, explaining what broke
	Evidence map[string]any `json:"evidence,omitzero"`
	// Record of who acknowledged an alert and when
	Ack *Ack `json:"ack,omitzero"`
	// Record of how an alert was resolved and by whom
	Resolution *Resolution `json:"resolution,omitzero"`
	// A time-boxed, operator-initiated mute of an alert's notifications. While
	// `until` is in the future the alert keeps failing and keeps counting
	// against period-green — only its notifications are suppressed.
	//
	Snooze *Snooze `json:"snooze,omitzero"`
	// Key/value pairs copied from the rule that raised the alert
	Labels map[string]string `json:"labels,omitzero"`
	// When the alert was created
	CreatedAt time.Time `json:"createdAt"`
	// When the alert was last modified
	UpdatedAt time.Time `json:"updatedAt"`
}

func (a Alert) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Alert) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Alert) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *Alert) GetRuleID() string {
	if a == nil {
		return ""
	}
	return a.RuleID
}

func (a *Alert) GetFingerprint() string {
	if a == nil {
		return ""
	}
	return a.Fingerprint
}

func (a *Alert) GetPeriodID() string {
	if a == nil {
		return ""
	}
	return a.PeriodID
}

func (a *Alert) GetStatus() Status {
	if a == nil {
		return Status("")
	}
	return a.Status
}

func (a *Alert) GetSeverity() Severity {
	if a == nil {
		return Severity("")
	}
	return a.Severity
}

func (a *Alert) GetFirstSeenAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.FirstSeenAt
}

func (a *Alert) GetLastSeenAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.LastSeenAt
}

func (a *Alert) GetOccurrenceCount() int64 {
	if a == nil {
		return 0
	}
	return a.OccurrenceCount
}

func (a *Alert) GetLastEvaluationID() string {
	if a == nil {
		return ""
	}
	return a.LastEvaluationID
}

func (a *Alert) GetEvidence() map[string]any {
	if a == nil {
		return nil
	}
	return a.Evidence
}

func (a *Alert) GetAck() *Ack {
	if a == nil {
		return nil
	}
	return a.Ack
}

func (a *Alert) GetResolution() *Resolution {
	if a == nil {
		return nil
	}
	return a.Resolution
}

func (a *Alert) GetSnooze() *Snooze {
	if a == nil {
		return nil
	}
	return a.Snooze
}

func (a *Alert) GetLabels() map[string]string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *Alert) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *Alert) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}
