// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Cadence - Reconciliation rhythm. Scopes each failing fingerprint into a period so a
// March break and an April break are distinct, independently-closable cases.
// `continuous` (default) is a single unbounded period (live monitoring).
type Cadence string

const (
	CadenceContinuous Cadence = "continuous"
	CadenceDaily      Cadence = "daily"
	CadenceWeekly     Cadence = "weekly"
	CadenceMonthly    Cadence = "monthly"
)

func (e Cadence) ToPointer() *Cadence {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Cadence) IsExact() bool {
	if e != nil {
		switch *e {
		case "continuous", "daily", "weekly", "monthly":
			return true
		}
	}
	return false
}
