// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorResponse - Error response
type ErrorResponse struct {
	// Machine-readable error code identifying the failure
	ErrorCode string `json:"errorCode"`
	// Human-readable description of the error
	ErrorMessage string `json:"errorMessage"`
	// Optional link carrying additional context about the error
	Details *string `json:"details,omitzero"`
}

func (e *ErrorResponse) GetErrorCode() string {
	if e == nil {
		return ""
	}
	return e.ErrorCode
}

func (e *ErrorResponse) GetErrorMessage() string {
	if e == nil {
		return ""
	}
	return e.ErrorMessage
}

func (e *ErrorResponse) GetDetails() *string {
	if e == nil {
		return nil
	}
	return e.Details
}
