// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EvaluationResponse - OK
type EvaluationResponse struct {
	// One run of a rule, carrying its outcome and cost
	Data Evaluation `json:"data"`
}

func (e *EvaluationResponse) GetData() Evaluation {
	if e == nil {
		return Evaluation{}
	}
	return e.Data
}
