// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EvaluationsCursorResponseCursor - Paginated cursor wrapping the list of evaluations
type EvaluationsCursorResponseCursor struct {
	PageSize int64        `json:"pageSize"`
	HasMore  bool         `json:"hasMore"`
	Previous *string      `json:"previous,omitzero"`
	Next     *string      `json:"next,omitzero"`
	Data     []Evaluation `json:"data"`
}

func (e *EvaluationsCursorResponseCursor) GetPageSize() int64 {
	if e == nil {
		return 0
	}
	return e.PageSize
}

func (e *EvaluationsCursorResponseCursor) GetHasMore() bool {
	if e == nil {
		return false
	}
	return e.HasMore
}

func (e *EvaluationsCursorResponseCursor) GetPrevious() *string {
	if e == nil {
		return nil
	}
	return e.Previous
}

func (e *EvaluationsCursorResponseCursor) GetNext() *string {
	if e == nil {
		return nil
	}
	return e.Next
}

func (e *EvaluationsCursorResponseCursor) GetData() []Evaluation {
	if e == nil {
		return []Evaluation{}
	}
	return e.Data
}

// EvaluationsCursorResponse - OK
type EvaluationsCursorResponse struct {
	// Paginated cursor wrapping the list of evaluations
	Cursor EvaluationsCursorResponseCursor `json:"cursor"`
}

func (e *EvaluationsCursorResponse) GetCursor() EvaluationsCursorResponseCursor {
	if e == nil {
		return EvaluationsCursorResponseCursor{}
	}
	return e.Cursor
}
