// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PolicyRequest struct {
	// Human-readable name for the policy
	Name string `json:"name"`
	// Name of the ledger the policy reconciles against
	LedgerName string `json:"ledgerName"`
	// Filter selecting the ledger accounts whose balances are reconciled
	LedgerQuery map[string]any `json:"ledgerQuery"`
	// Identifier of the payments pool the ledger side is compared against
	PaymentsPoolID string `json:"paymentsPoolID"`
}

func (p *PolicyRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PolicyRequest) GetLedgerName() string {
	if p == nil {
		return ""
	}
	return p.LedgerName
}

func (p *PolicyRequest) GetLedgerQuery() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.LedgerQuery
}

func (p *PolicyRequest) GetPaymentsPoolID() string {
	if p == nil {
		return ""
	}
	return p.PaymentsPoolID
}
