// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PolicyResponse - OK
type PolicyResponse struct {
	// A reconciliation policy pairing a ledger query with a payments pool
	Data Policy `json:"data"`
}

func (p *PolicyResponse) GetData() Policy {
	if p == nil {
		return Policy{}
	}
	return p.Data
}
