// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PoliciesCursorResponseCursor - Paginated cursor wrapping the list of policies
type PoliciesCursorResponseCursor struct {
	PageSize int64    `json:"pageSize"`
	HasMore  bool     `json:"hasMore"`
	Previous *string  `json:"previous,omitzero"`
	Next     *string  `json:"next,omitzero"`
	Data     []Policy `json:"data"`
}

func (p *PoliciesCursorResponseCursor) GetPageSize() int64 {
	if p == nil {
		return 0
	}
	return p.PageSize
}

func (p *PoliciesCursorResponseCursor) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PoliciesCursorResponseCursor) GetPrevious() *string {
	if p == nil {
		return nil
	}
	return p.Previous
}

func (p *PoliciesCursorResponseCursor) GetNext() *string {
	if p == nil {
		return nil
	}
	return p.Next
}

func (p *PoliciesCursorResponseCursor) GetData() []Policy {
	if p == nil {
		return []Policy{}
	}
	return p.Data
}

// PoliciesCursorResponse - OK
type PoliciesCursorResponse struct {
	// Paginated cursor wrapping the list of policies
	Cursor PoliciesCursorResponseCursor `json:"cursor"`
}

func (p *PoliciesCursorResponse) GetCursor() PoliciesCursorResponseCursor {
	if p == nil {
		return PoliciesCursorResponseCursor{}
	}
	return p.Cursor
}
