// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

// Policy - A reconciliation policy pairing a ledger query with a payments pool
type Policy struct {
	// Unique identifier of the policy
	ID string `json:"id"`
	// Human-readable name of the policy
	Name string `json:"name"`
	// When the policy was created
	CreatedAt time.Time `json:"createdAt"`
	// Name of the ledger the policy reconciles against
	LedgerName string `json:"ledgerName"`
	// Filter selecting the ledger accounts whose balances are reconciled
	LedgerQuery map[string]any `json:"ledgerQuery"`
	// Identifier of the payments pool the ledger side is compared against
	PaymentsPoolID string `json:"paymentsPoolID"`
}

func (p Policy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Policy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Policy) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Policy) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Policy) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Policy) GetLedgerName() string {
	if p == nil {
		return ""
	}
	return p.LedgerName
}

func (p *Policy) GetLedgerQuery() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.LedgerQuery
}

func (p *Policy) GetPaymentsPoolID() string {
	if p == nil {
		return ""
	}
	return p.PaymentsPoolID
}
