// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"math/big"
	"time"
)

// Reconciliation - One run of a policy, comparing both sides and reporting the drift between them
type Reconciliation struct {
	// Unique identifier of the reconciliation run
	ID string `json:"id"`
	// Identifier of the policy this run applied
	PolicyID string `json:"policyID"`
	// When the reconciliation was run
	CreatedAt time.Time `json:"createdAt"`
	// Point in time at which the ledger side was evaluated
	ReconciledAtLedger time.Time `json:"reconciledAtLedger"`
	// Point in time at which the payments side was evaluated
	ReconciledAtPayments time.Time `json:"reconciledAtPayments"`
	// Outcome of the reconciliation run
	Status string `json:"status"`
	// Balances observed on the payments side, keyed by asset
	PaymentsBalances map[string]*big.Int `json:"paymentsBalances"`
	// Balances observed on the ledger side, keyed by asset
	LedgerBalances map[string]*big.Int `json:"ledgerBalances"`
	// Difference between the two sides, keyed by asset. All-zero means the sides agree
	DriftBalances map[string]*big.Int `json:"driftBalances"`
	// Why the run failed, when its status reports an error
	Error *string `json:"error,omitzero"`
}

func (r Reconciliation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Reconciliation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Reconciliation) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Reconciliation) GetPolicyID() string {
	if r == nil {
		return ""
	}
	return r.PolicyID
}

func (r *Reconciliation) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *Reconciliation) GetReconciledAtLedger() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ReconciledAtLedger
}

func (r *Reconciliation) GetReconciledAtPayments() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ReconciledAtPayments
}

func (r *Reconciliation) GetStatus() string {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *Reconciliation) GetPaymentsBalances() map[string]*big.Int {
	if r == nil {
		return map[string]*big.Int{}
	}
	return r.PaymentsBalances
}

func (r *Reconciliation) GetLedgerBalances() map[string]*big.Int {
	if r == nil {
		return map[string]*big.Int{}
	}
	return r.LedgerBalances
}

func (r *Reconciliation) GetDriftBalances() map[string]*big.Int {
	if r == nil {
		return map[string]*big.Int{}
	}
	return r.DriftBalances
}

func (r *Reconciliation) GetError() *string {
	if r == nil {
		return nil
	}
	return r.Error
}
