// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ReconciliationResponse - OK
type ReconciliationResponse struct {
	// One run of a policy, comparing both sides and reporting the drift between them
	Data Reconciliation `json:"data"`
}

func (r *ReconciliationResponse) GetData() Reconciliation {
	if r == nil {
		return Reconciliation{}
	}
	return r.Data
}
