// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ReconciliationsCursorResponseCursor - Paginated cursor wrapping the list of reconciliations
type ReconciliationsCursorResponseCursor struct {
	PageSize int64            `json:"pageSize"`
	HasMore  bool             `json:"hasMore"`
	Previous *string          `json:"previous,omitzero"`
	Next     *string          `json:"next,omitzero"`
	Data     []Reconciliation `json:"data"`
}

func (r *ReconciliationsCursorResponseCursor) GetPageSize() int64 {
	if r == nil {
		return 0
	}
	return r.PageSize
}

func (r *ReconciliationsCursorResponseCursor) GetHasMore() bool {
	if r == nil {
		return false
	}
	return r.HasMore
}

func (r *ReconciliationsCursorResponseCursor) GetPrevious() *string {
	if r == nil {
		return nil
	}
	return r.Previous
}

func (r *ReconciliationsCursorResponseCursor) GetNext() *string {
	if r == nil {
		return nil
	}
	return r.Next
}

func (r *ReconciliationsCursorResponseCursor) GetData() []Reconciliation {
	if r == nil {
		return []Reconciliation{}
	}
	return r.Data
}

// ReconciliationsCursorResponse - OK
type ReconciliationsCursorResponse struct {
	// Paginated cursor wrapping the list of reconciliations
	Cursor ReconciliationsCursorResponseCursor `json:"cursor"`
}

func (r *ReconciliationsCursorResponse) GetCursor() ReconciliationsCursorResponseCursor {
	if r == nil {
		return ReconciliationsCursorResponseCursor{}
	}
	return r.Cursor
}
