// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

type ReconciliationRequest struct {
	// Point in time at which the ledger side is evaluated
	ReconciledAtLedger time.Time `json:"reconciledAtLedger"`
	// Point in time at which the payments side is evaluated
	ReconciledAtPayments time.Time `json:"reconciledAtPayments"`
}

func (r ReconciliationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReconciliationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReconciliationRequest) GetReconciledAtLedger() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ReconciledAtLedger
}

func (r *ReconciliationRequest) GetReconciledAtPayments() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ReconciledAtPayments
}
