// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
)

// ResolveAlertRequest - Mark an alert resolved. When `transactionRefs` is non-empty the
// resolution kind is recorded as `fixed_by_booking`.
type ResolveAlertRequest struct {
	// Who is resolving the alert
	By string `json:"by"`
	// Free-text note to record with the resolution
	Note *string `json:"note,omitzero"`
	// References of the transactions booked to correct the break. Supplying any records the resolution as fixed_by_booking
	TransactionRefs []string `json:"transactionRefs,omitzero"`
}

func (r ResolveAlertRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResolveAlertRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResolveAlertRequest) GetBy() string {
	if r == nil {
		return ""
	}
	return r.By
}

func (r *ResolveAlertRequest) GetNote() *string {
	if r == nil {
		return nil
	}
	return r.Note
}

func (r *ResolveAlertRequest) GetTransactionRefs() []string {
	if r == nil {
		return nil
	}
	return r.TransactionRefs
}
