// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

// ResolutionKind - How the alert was resolved, whether automatically, by booking a correcting transaction, or by business acceptance
type ResolutionKind string

const (
	ResolutionKindAuto               ResolutionKind = "auto"
	ResolutionKindFixedByBooking     ResolutionKind = "fixed_by_booking"
	ResolutionKindAcceptedByBusiness ResolutionKind = "accepted_by_business"
)

func (e ResolutionKind) ToPointer() *ResolutionKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ResolutionKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "fixed_by_booking", "accepted_by_business":
			return true
		}
	}
	return false
}

// Resolution - Record of how an alert was resolved and by whom
type Resolution struct {
	// How the alert was resolved, whether automatically, by booking a correcting transaction, or by business acceptance
	Kind ResolutionKind `json:"kind"`
	// Who resolved the alert
	By string `json:"by"`
	// When the alert was resolved
	At time.Time `json:"at"`
	// Free-text note left by whoever resolved the alert
	Note *string `json:"note,omitzero"`
	// References of the transactions booked to correct the break
	TransactionRefs []string `json:"transactionRefs,omitzero"`
	// The alert's evidence captured at resolution time, kept for audit
	EvidenceSnapshot map[string]any `json:"evidenceSnapshot,omitzero"`
}

func (r Resolution) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Resolution) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Resolution) GetKind() ResolutionKind {
	if r == nil {
		return ResolutionKind("")
	}
	return r.Kind
}

func (r *Resolution) GetBy() string {
	if r == nil {
		return ""
	}
	return r.By
}

func (r *Resolution) GetAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.At
}

func (r *Resolution) GetNote() *string {
	if r == nil {
		return nil
	}
	return r.Note
}

func (r *Resolution) GetTransactionRefs() []string {
	if r == nil {
		return nil
	}
	return r.TransactionRefs
}

func (r *Resolution) GetEvidenceSnapshot() map[string]any {
	if r == nil {
		return nil
	}
	return r.EvidenceSnapshot
}
