// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RulesCursorResponseCursor - Paginated cursor wrapping the list of rules
type RulesCursorResponseCursor struct {
	PageSize int64   `json:"pageSize"`
	HasMore  bool    `json:"hasMore"`
	Previous *string `json:"previous,omitzero"`
	Next     *string `json:"next,omitzero"`
	Data     []Rule  `json:"data"`
}

func (r *RulesCursorResponseCursor) GetPageSize() int64 {
	if r == nil {
		return 0
	}
	return r.PageSize
}

func (r *RulesCursorResponseCursor) GetHasMore() bool {
	if r == nil {
		return false
	}
	return r.HasMore
}

func (r *RulesCursorResponseCursor) GetPrevious() *string {
	if r == nil {
		return nil
	}
	return r.Previous
}

func (r *RulesCursorResponseCursor) GetNext() *string {
	if r == nil {
		return nil
	}
	return r.Next
}

func (r *RulesCursorResponseCursor) GetData() []Rule {
	if r == nil {
		return []Rule{}
	}
	return r.Data
}

// RulesCursorResponse - OK
type RulesCursorResponse struct {
	// Paginated cursor wrapping the list of rules
	Cursor RulesCursorResponseCursor `json:"cursor"`
}

func (r *RulesCursorResponse) GetCursor() RulesCursorResponseCursor {
	if r == nil {
		return RulesCursorResponseCursor{}
	}
	return r.Cursor
}
