// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
)

type RuleRequest struct {
	// Human-readable name for the rule
	Name string `json:"name"`
	// Which built-in check a rule applies, determining the shape of its templateSpec
	TemplateKind TemplateKind `json:"templateKind"`
	// Parameters for the chosen template, whose shape depends on templateKind
	TemplateSpec map[string]any `json:"templateSpec"`
	// How serious an alert is, used to route and prioritise notifications
	Severity *Severity `json:"severity,omitzero"`
	// Reconciliation rhythm. Scopes each failing fingerprint into a period so a
	// March break and an April break are distinct, independently-closable cases.
	// `continuous` (default) is a single unbounded period (live monitoring).
	//
	Cadence *Cadence `default:"continuous" json:"cadence"`
	// When a rule runs, either on demand or on a cron expression
	Schedule *Schedule `json:"schedule,omitzero"`
	// Channels to notify when this rule raises an alert
	Notifications []string `json:"notifications,omitzero"`
	// Arbitrary key/value pairs to attach to the rule and copy onto the alerts it raises
	Labels map[string]string `json:"labels,omitzero"`
	// Whether the rule should be evaluated. Defaults to enabled
	Enabled *bool `json:"enabled,omitzero"`
}

func (r RuleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RuleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RuleRequest) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RuleRequest) GetTemplateKind() TemplateKind {
	if r == nil {
		return TemplateKind("")
	}
	return r.TemplateKind
}

func (r *RuleRequest) GetTemplateSpec() map[string]any {
	if r == nil {
		return map[string]any{}
	}
	return r.TemplateSpec
}

func (r *RuleRequest) GetSeverity() *Severity {
	if r == nil {
		return nil
	}
	return r.Severity
}

func (r *RuleRequest) GetCadence() *Cadence {
	if r == nil {
		return nil
	}
	return r.Cadence
}

func (r *RuleRequest) GetSchedule() *Schedule {
	if r == nil {
		return nil
	}
	return r.Schedule
}

func (r *RuleRequest) GetNotifications() []string {
	if r == nil {
		return nil
	}
	return r.Notifications
}

func (r *RuleRequest) GetLabels() map[string]string {
	if r == nil {
		return nil
	}
	return r.Labels
}

func (r *RuleRequest) GetEnabled() *bool {
	if r == nil {
		return nil
	}
	return r.Enabled
}
