// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RuleResponse - OK
type RuleResponse struct {
	// A monitoring rule evaluated on a cadence, raising alerts when it fails
	Data Rule `json:"data"`
}

func (r *RuleResponse) GetData() Rule {
	if r == nil {
		return Rule{}
	}
	return r.Data
}
