// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
)

// RulePatchRequest - Partial update — only fields supplied are applied.
type RulePatchRequest struct {
	// New human-readable name for the rule
	Name *string `json:"name,omitzero"`
	// Which built-in check a rule applies, determining the shape of its templateSpec
	TemplateKind *TemplateKind `json:"templateKind,omitzero"`
	// New parameters for the template, whose shape depends on templateKind
	TemplateSpec map[string]any `json:"templateSpec,omitzero"`
	// Whether the rule should be evaluated
	Enabled *bool `json:"enabled,omitzero"`
	// How serious an alert is, used to route and prioritise notifications
	Severity *Severity `json:"severity,omitzero"`
	// When a rule runs, either on demand or on a cron expression
	Schedule *Schedule `json:"schedule,omitzero"`
	// New set of channels to notify when this rule raises an alert
	Notifications []string `json:"notifications,omitzero"`
	// New set of key/value pairs attached to the rule
	Labels map[string]string `json:"labels,omitzero"`
}

func (r RulePatchRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RulePatchRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RulePatchRequest) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RulePatchRequest) GetTemplateKind() *TemplateKind {
	if r == nil {
		return nil
	}
	return r.TemplateKind
}

func (r *RulePatchRequest) GetTemplateSpec() map[string]any {
	if r == nil {
		return nil
	}
	return r.TemplateSpec
}

func (r *RulePatchRequest) GetEnabled() *bool {
	if r == nil {
		return nil
	}
	return r.Enabled
}

func (r *RulePatchRequest) GetSeverity() *Severity {
	if r == nil {
		return nil
	}
	return r.Severity
}

func (r *RulePatchRequest) GetSchedule() *Schedule {
	if r == nil {
		return nil
	}
	return r.Schedule
}

func (r *RulePatchRequest) GetNotifications() []string {
	if r == nil {
		return nil
	}
	return r.Notifications
}

func (r *RulePatchRequest) GetLabels() map[string]string {
	if r == nil {
		return nil
	}
	return r.Labels
}
