// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
)

type RuleRequest struct {
	// Human-readable name for the rule
	Name string `json:"name"`
	// Which built-in check a rule applies, determining the shape of its templateSpec
	TemplateKind TemplateKind `json:"templateKind"`
	// Parameters for the chosen template, whose shape depends on templateKind
	TemplateSpec map[string]any `json:"templateSpec"`
	// How serious an alert is, used to route and prioritise notifications
	Severity *Severity `json:"severity,omitzero"`
	// How long a reconciliation period lasts. Scopes each failing fingerprint
	// into a period so a March break and an April break are distinct,
	// independently-closable cases.
	//
	// Omit the key to get `continuous`, a single unbounded period (live
	// monitoring). There is deliberately no schema-level `default`: SDK
	// generators materialize defaults into the serialized body, which would
	// make an omitted key indistinguishable from an explicit one and collide
	// with the deprecated `cadence` alias. The server owns the default.
	//
	// This is not how often the rule runs — that is `schedule`, and the two are
	// independent: an hourly schedule with a `monthly` period type is normal.
	// The period type determines the `periodID` an alert is filed under:
	// `monthly` yields `2026-07`.
	//
	PeriodType *PeriodType `json:"periodType,omitzero"`
	// Deprecated alias of `periodType`. Same members. Use `periodType`; this is
	// removed at the next API major.
	//
	// Kept as its own component so regenerated SDKs keep emitting the
	// `Cadence` type and its constants — dropping it would delete
	// `CadenceMonthly` and friends from generated clients and break code that
	// compiles today, even though the wire contract stays compatible.
	//
	// On requests either key is accepted. If both carry a value and the values
	// differ the request is rejected with 400 rather than one being chosen
	// silently; an empty `cadence` counts as unset rather than as a
	// conflicting value.
	//
	// On responses the server always emits both keys, mirroring, but neither
	// is listed in the `Rule` required set. That understates the guarantee on
	// purpose. A required property with no schema default generates a value
	// type in Go, which would turn the published `Rule.Cadence *Cadence` and
	// `GetCadence() *Cadence` into non-pointers and break existing consumers;
	// optional-without-default reproduces the published pointer signatures.
	// The default cannot come back, because generators materialize it into
	// request bodies and that collides with this alias. Both become required
	// again at the next API major, when `cadence` goes.
	//
	// Servers before 2.5.0 do not know `periodType` and ignore it, falling
	// back to `continuous`. Normally that cannot bite you: `periodType`
	// reaches clients via an SDK regenerated from this spec, which only exists
	// once 2.5.0 is released. If you need determinism while a fleet is
	// mid-upgrade, send both keys with equal values — accepted on every
	// version.
	//
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Cadence *Cadence `json:"cadence,omitzero"`
	// When a rule runs, either on demand or on a cron expression
	Schedule *Schedule `json:"schedule,omitzero"`
	// Channels to notify when this rule raises an alert
	Notifications []string `json:"notifications,omitzero"`
	// Arbitrary key/value pairs to attach to the rule and copy onto the alerts it raises
	Labels map[string]string `json:"labels,omitzero"`
	// Whether the rule should be evaluated. Defaults to enabled
	Enabled *bool `json:"enabled,omitzero"`
}

func (r RuleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RuleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RuleRequest) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RuleRequest) GetTemplateKind() TemplateKind {
	if r == nil {
		return TemplateKind("")
	}
	return r.TemplateKind
}

func (r *RuleRequest) GetTemplateSpec() map[string]any {
	if r == nil {
		return map[string]any{}
	}
	return r.TemplateSpec
}

func (r *RuleRequest) GetSeverity() *Severity {
	if r == nil {
		return nil
	}
	return r.Severity
}

func (r *RuleRequest) GetPeriodType() *PeriodType {
	if r == nil {
		return nil
	}
	return r.PeriodType
}

func (r *RuleRequest) GetCadence() *Cadence {
	if r == nil {
		return nil
	}
	return r.Cadence
}

func (r *RuleRequest) GetSchedule() *Schedule {
	if r == nil {
		return nil
	}
	return r.Schedule
}

func (r *RuleRequest) GetNotifications() []string {
	if r == nil {
		return nil
	}
	return r.Notifications
}

func (r *RuleRequest) GetLabels() map[string]string {
	if r == nil {
		return nil
	}
	return r.Labels
}

func (r *RuleRequest) GetEnabled() *bool {
	if r == nil {
		return nil
	}
	return r.Enabled
}
