// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

// Rule - A monitoring rule evaluated on a cadence, raising alerts when it fails
type Rule struct {
	// Unique identifier of the rule
	ID string `json:"id"`
	// Human-readable name of the rule
	Name string `json:"name"`
	// Which built-in check a rule applies, determining the shape of its templateSpec
	TemplateKind TemplateKind `json:"templateKind"`
	// Parameters for the chosen template, whose shape depends on templateKind
	TemplateSpec map[string]any `json:"templateSpec"`
	// Representative CEL for human explanation; not the runtime program.
	ExplanationCEL *string `json:"explanationCEL,omitzero"`
	// Whether the rule is evaluated. Disabled rules produce no evaluations
	Enabled bool `json:"enabled"`
	// How serious an alert is, used to route and prioritise notifications
	Severity Severity `json:"severity"`
	// Reconciliation rhythm. Scopes each failing fingerprint into a period so a
	// March break and an April break are distinct, independently-closable cases.
	// `continuous` (default) is a single unbounded period (live monitoring).
	//
	Cadence *Cadence `default:"continuous" json:"cadence"`
	// When a rule runs, either on demand or on a cron expression
	Schedule *Schedule `json:"schedule,omitzero"`
	// Channels notified when this rule raises an alert
	Notifications []string `json:"notifications,omitzero"`
	// Arbitrary key/value pairs attached to the rule and copied onto the alerts it raises
	Labels map[string]string `json:"labels,omitzero"`
	// When the rule was created
	CreatedAt time.Time `json:"createdAt"`
	// When the rule was last modified
	UpdatedAt time.Time `json:"updatedAt"`
}

func (r Rule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Rule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Rule) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Rule) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *Rule) GetTemplateKind() TemplateKind {
	if r == nil {
		return TemplateKind("")
	}
	return r.TemplateKind
}

func (r *Rule) GetTemplateSpec() map[string]any {
	if r == nil {
		return map[string]any{}
	}
	return r.TemplateSpec
}

func (r *Rule) GetExplanationCEL() *string {
	if r == nil {
		return nil
	}
	return r.ExplanationCEL
}

func (r *Rule) GetEnabled() bool {
	if r == nil {
		return false
	}
	return r.Enabled
}

func (r *Rule) GetSeverity() Severity {
	if r == nil {
		return Severity("")
	}
	return r.Severity
}

func (r *Rule) GetCadence() *Cadence {
	if r == nil {
		return nil
	}
	return r.Cadence
}

func (r *Rule) GetSchedule() *Schedule {
	if r == nil {
		return nil
	}
	return r.Schedule
}

func (r *Rule) GetNotifications() []string {
	if r == nil {
		return nil
	}
	return r.Notifications
}

func (r *Rule) GetLabels() map[string]string {
	if r == nil {
		return nil
	}
	return r.Labels
}

func (r *Rule) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *Rule) GetUpdatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.UpdatedAt
}
