// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ScheduleKind - Whether the rule runs only when triggered or on a recurring cron schedule
type ScheduleKind string

const (
	ScheduleKindOnDemand ScheduleKind = "on_demand"
	ScheduleKindCron     ScheduleKind = "cron"
)

func (e ScheduleKind) ToPointer() *ScheduleKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ScheduleKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "on_demand", "cron":
			return true
		}
	}
	return false
}

// Schedule - When a rule runs, either on demand or on a cron expression
type Schedule struct {
	// Whether the rule runs only when triggered or on a recurring cron schedule
	Kind ScheduleKind `json:"kind"`
	// Cron expression driving the schedule, required when kind is cron
	Expr *string `json:"expr,omitzero"`
	// Timezone the cron expression is interpreted in
	Tz *string `json:"tz,omitzero"`
	// Go duration string
	SafetyMargin *string `json:"safetyMargin,omitzero"`
}

func (s *Schedule) GetKind() ScheduleKind {
	if s == nil {
		return ScheduleKind("")
	}
	return s.Kind
}

func (s *Schedule) GetExpr() *string {
	if s == nil {
		return nil
	}
	return s.Expr
}

func (s *Schedule) GetTz() *string {
	if s == nil {
		return nil
	}
	return s.Tz
}

func (s *Schedule) GetSafetyMargin() *string {
	if s == nil {
		return nil
	}
	return s.SafetyMargin
}
