// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	Authorization string `security:"scheme,type=apiKey,subtype=header,name=Authorization"`
}

func (s *Security) GetAuthorization() string {
	if s == nil {
		return ""
	}
	return s.Authorization
}
