// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ServerInfo - Server information
type ServerInfo struct {
	// Version of the reconciliation service
	Version string `json:"version"`
}

func (s *ServerInfo) GetVersion() string {
	if s == nil {
		return ""
	}
	return s.Version
}
