// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Severity - How serious an alert is, used to route and prioritise notifications
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

func (e Severity) ToPointer() *Severity {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Severity) IsExact() bool {
	if e != nil {
		switch *e {
		case "info", "low", "medium", "high", "critical":
			return true
		}
	}
	return false
}
