// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

// SnoozeAlertRequest - Mute an alert's notifications until `until` (which must be in the future).
type SnoozeAlertRequest struct {
	// Who is snoozing the alert
	By string `json:"by"`
	// When the mute expires and notifications resume. Must be in the future
	Until time.Time `json:"until"`
	// Free-text note to record with the snooze
	Note *string `json:"note,omitzero"`
}

func (s SnoozeAlertRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SnoozeAlertRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SnoozeAlertRequest) GetBy() string {
	if s == nil {
		return ""
	}
	return s.By
}

func (s *SnoozeAlertRequest) GetUntil() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.Until
}

func (s *SnoozeAlertRequest) GetNote() *string {
	if s == nil {
		return nil
	}
	return s.Note
}
