// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"time"
)

// Snooze - A time-boxed, operator-initiated mute of an alert's notifications. While
// `until` is in the future the alert keeps failing and keeps counting
// against period-green — only its notifications are suppressed.
type Snooze struct {
	// When the mute expires and notifications resume. Must be in the future
	Until time.Time `json:"until"`
	// Who snoozed the alert
	By string `json:"by"`
	// When the alert was snoozed
	At time.Time `json:"at"`
	// Free-text note left by whoever snoozed the alert
	Note *string `json:"note,omitzero"`
}

func (s Snooze) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Snooze) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Snooze) GetUntil() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.Until
}

func (s *Snooze) GetBy() string {
	if s == nil {
		return ""
	}
	return s.By
}

func (s *Snooze) GetAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.At
}

func (s *Snooze) GetNote() *string {
	if s == nil {
		return nil
	}
	return s.Note
}
