// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TemplateKind - Which built-in check a rule applies, determining the shape of its templateSpec
type TemplateKind string

const (
	TemplateKindLedgerVsPoolDrift TemplateKind = "ledger_vs_pool_drift"
	TemplateKindLedgerInvariant   TemplateKind = "ledger_invariant"
	TemplateKindAccountThreshold  TemplateKind = "account_threshold"
	TemplateKindSourceParity      TemplateKind = "source_parity"
)

func (e TemplateKind) ToPointer() *TemplateKind {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TemplateKind) IsExact() bool {
	if e != nil {
		switch *e {
		case "ledger_vs_pool_drift", "ledger_invariant", "account_threshold", "source_parity":
			return true
		}
	}
	return false
}
