// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UnsnoozeAlertRequest struct {
	// Who is lifting the snooze
	By string `json:"by"`
}

func (u *UnsnoozeAlertRequest) GetBy() string {
	if u == nil {
		return ""
	}
	return u.By
}
