package audit

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the generated half of the inventory: the totals table, the
// per-family operation tables, and the baseline mapping table. The reasoning,
// evidence and gate discussion live in the hand-written inventory document,
// which links to this file.
func (r *Report) Markdown() string {
	var b strings.Builder

	b.WriteString("<!-- Code generated by plugins/fctl/cmd/specaudit; DO NOT EDIT. -->\n\n")
	b.WriteString("# Reconciliation operation inventory (generated)\n\n")
	fmt.Fprintf(&b, "Source document: `%s` (repository root)\n\n", r.SpecDocument)
	fmt.Fprintf(&b, "Reconciliation revision: `%s`\n\n", r.ProductRevision)
	fmt.Fprintf(&b, "Generated-client OpenAPI SHA-256: `%s`\n\n", r.ClientSpecSHA256)
	fmt.Fprintf(&b, "Legacy fctl baseline revision: `%s`\n\n", r.BaselineRevision)
	fmt.Fprintf(&b, "fctl-v2 programme revision: `%s`\n\n", r.FctlV2Revision)
	fmt.Fprintf(&b, "Document `info.version`: `%s`\n\n", r.Document.Version)

	if len(r.UndefinedSecuritySchemes) > 0 {
		fmt.Fprintf(&b,
			"> **Contract defect.** %s referenced by operations but not defined in `components.securitySchemes` (see divergence D2).\n\n",
			codeList(r.UndefinedSecuritySchemes))
	}

	b.WriteString("## Totals\n\n")
	b.WriteString("| Count | Value |\n|---|---:|\n")
	t := r.Totals
	for _, row := range [][2]any{
		{"Operations in document", t.SpecOperations},
		{"Unique operationIds", t.UniqueOperationIDs},
		{"Operations declaring a security block", t.OperationsWithDeclaredScopes},
		{"Operations marked deprecated", t.DeprecatedOperations},
		{"Legacy fctl `reconciliation` commands (executable leaves)", t.BaselineCommands},
		{"Legacy commands mapped onto a current operation", t.BaselineMapped},
		{"Legacy commands excluded with evidence", t.BaselineExcluded},
		{"Operations in the first tranche (policies + reconciliations)", t.FrozenOperations},
		{"Operations recorded but outside the first tranche", t.RecordedOperations},
		{"Operations reached by the legacy baseline", t.WithBaseline},
		{"Operations with no legacy precedent", t.WithoutBaseline},
		{"Operations carrying a blocker", t.Blocked},
		{"First-tranche operations carrying a blocker", t.FrozenBlocked},
		{"Operations with no recorded blocker", t.Admissible},
		{"First-tranche operations with no recorded blocker", t.FrozenAdmissible},
		{"Recorded SDK-generation blockers", t.GenerationBlockers},
		{"Recorded spec-versus-server divergences", t.Divergences},
	} {
		fmt.Fprintf(&b, "| %v | %v |\n", row[0], row[1])
	}

	b.WriteString("\n## Operations by family\n\n")
	groups := r.ByFamily()
	families := make([]Family, 0, len(groups))
	for f := range groups {
		families = append(families, f)
	}
	sort.Slice(families, func(i, j int) bool { return families[i] < families[j] })

	for _, f := range families {
		tranche := "recorded, outside the first tranche"
		if IsFrozen(f) {
			tranche = "first tranche"
		}
		fmt.Fprintf(&b, "### %s (%d) — %s\n\n", f, len(groups[f]), tranche)
		b.WriteString("| operationId | Method | Path | Scopes | Request | Success | Risk | Legacy command(s) | Blockers |\n")
		b.WriteString("|---|---|---|---|---|---|---|---|---|\n")
		for _, rec := range groups[f] {
			fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s | %s | %s | %s | %s |\n",
				rec.OperationID,
				rec.Method,
				rec.Path,
				scopeCell(rec.Operation),
				bodyCell(rec.RequestBody),
				successCell(rec.Operation),
				riskCell(rec.Risk),
				commandCell(rec.BaselineCommands),
				listCell(rec.Blockers),
			)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Legacy baseline mapping\n\n")
	b.WriteString("| Legacy command | Aliases | Source file | operationId(s) |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, c := range Baseline {
		target := "— (excluded)"
		if len(c.Ops) > 0 {
			target = codeList(c.Ops)
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s |\n",
			escapeCell(c.Path), listCell(c.Aliases), c.SourceFile, target)
	}

	b.WriteString("\n## Operations with no legacy precedent\n\n")
	b.WriteString("| operationId | Family | Method | Path |\n|---|---|---|---|\n")
	for _, rec := range r.Operations {
		if len(rec.BaselineCommands) == 0 {
			fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` |\n", rec.OperationID, rec.Family, rec.Method, rec.Path)
		}
	}

	b.WriteString("\n## Deprecated operations in the document\n\n")
	deprecated := 0
	for _, rec := range r.Operations {
		if rec.Deprecated {
			if deprecated == 0 {
				b.WriteString("| operationId | Method | Path |\n|---|---|---|\n")
			}
			deprecated++
			fmt.Fprintf(&b, "| `%s` | %s | `%s` |\n", rec.OperationID, rec.Method, rec.Path)
		}
	}
	if deprecated == 0 {
		b.WriteString("None. No operation in the document is marked `deprecated`.\n")
	}

	return b.String()
}

func scopeCell(op Operation) string {
	if !op.HasSecurity {
		return "**none declared**"
	}
	if len(op.Scopes) == 0 {
		return "`[]`"
	}
	return codeList(op.Scopes)
}

func bodyCell(name string) string {
	if name == "" {
		return "—"
	}
	return "`" + name + "`"
}

func successCell(op Operation) string {
	if op.SuccessBody == "" {
		return op.SuccessCode + " (no body)"
	}
	return op.SuccessCode + " `" + op.SuccessBody + "`"
}

func riskCell(r Risk) string {
	var tags []string
	if r.Destructive {
		tags = append(tags, "destructive")
	}
	switch r.Secret {
	case SecretInbound:
		tags = append(tags, "secret:request")
	case SecretOutbound:
		tags = append(tags, "secret:response")
	}
	if r.DisplayOnce {
		tags = append(tags, "display-once")
	}
	if r.StateTransition {
		tags = append(tags, "state-transition")
	}
	if r.GetWithBody {
		tags = append(tags, "get-with-body")
	}
	if r.Paginated {
		tags = append(tags, "paginated")
	}
	if !r.ReplaySafe {
		tags = append(tags, "not-replay-safe")
	}
	if len(tags) == 0 {
		return "—"
	}
	return strings.Join(tags, ", ")
}

func commandCell(paths []string) string {
	if len(paths) == 0 {
		return "— (no legacy precedent)"
	}
	return codeList(paths)
}

func listCell(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	return strings.Join(items, ", ")
}

func codeList(items []string) string {
	quoted := make([]string, 0, len(items))
	for _, s := range items {
		quoted = append(quoted, "`"+escapeCell(s)+"`")
	}
	return strings.Join(quoted, "<br>")
}

// escapeCell escapes the pipes that legacy command paths carry (`<file>|-`), so
// they do not terminate the table cell they are rendered in.
func escapeCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
