// Code generated by internal/generateclient. DO NOT EDIT.

package utils

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

// unmarshalJSONLossless gives arbitrary JSON values json.Number leaves instead
// of float64 leaves, preserving integer and decimal tokens during round trips.
func unmarshalJSONLossless(data []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := decoder.Decode(destination); err != nil {
		return err
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		if err == nil {
			return fmt.Errorf("multiple JSON values")
		}
		return err
	}
	return nil
}
