// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

// ErrorResponse - Error response
type ErrorResponse struct {
	// Machine-readable error code identifying the failure
	ErrorCode string `json:"errorCode"`
	// Human-readable description of the error
	ErrorMessage string `json:"errorMessage"`
	// Optional link carrying additional context about the error
	Details  *string                 `json:"details,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
