// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type AcceptAlertRequest struct {
	// The alert ID.
	AlertID string                        `pathParam:"style=simple,explode=false,name=alertID"`
	Body    components.AcceptAlertRequest `request:"mediaType=application/json"`
}

func (a *AcceptAlertRequest) GetAlertID() string {
	if a == nil {
		return ""
	}
	return a.AlertID
}

func (a *AcceptAlertRequest) GetBody() components.AcceptAlertRequest {
	if a == nil {
		return components.AcceptAlertRequest{}
	}
	return a.Body
}

type AcceptAlertResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AlertResponse *components.AlertResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (a AcceptAlertResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AcceptAlertResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AcceptAlertResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AcceptAlertResponse) GetAlertResponse() *components.AlertResponse {
	if a == nil {
		return nil
	}
	return a.AlertResponse
}

func (a *AcceptAlertResponse) GetErrorResponse() *components.ErrorResponse {
	if a == nil {
		return nil
	}
	return a.ErrorResponse
}
