// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type AckAlertRequest struct {
	// The alert ID.
	AlertID string                     `pathParam:"style=simple,explode=false,name=alertID"`
	Body    components.AckAlertRequest `request:"mediaType=application/json"`
}

func (a *AckAlertRequest) GetAlertID() string {
	if a == nil {
		return ""
	}
	return a.AlertID
}

func (a *AckAlertRequest) GetBody() components.AckAlertRequest {
	if a == nil {
		return components.AckAlertRequest{}
	}
	return a.Body
}

type AckAlertResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AlertResponse *components.AlertResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (a AckAlertResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AckAlertResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AckAlertResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AckAlertResponse) GetAlertResponse() *components.AlertResponse {
	if a == nil {
		return nil
	}
	return a.AlertResponse
}

func (a *AckAlertResponse) GetErrorResponse() *components.ErrorResponse {
	if a == nil {
		return nil
	}
	return a.ErrorResponse
}
