// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type CreateRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RuleResponse *components.RuleResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (c CreateRuleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRuleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateRuleResponse) GetRuleResponse() *components.RuleResponse {
	if c == nil {
		return nil
	}
	return c.RuleResponse
}

func (c *CreateRuleResponse) GetErrorResponse() *components.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
