// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type CreatePolicyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PolicyResponse *components.PolicyResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (c CreatePolicyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePolicyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreatePolicyResponse) GetPolicyResponse() *components.PolicyResponse {
	if c == nil {
		return nil
	}
	return c.PolicyResponse
}

func (c *CreatePolicyResponse) GetErrorResponse() *components.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
