// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type DeletePolicyRequest struct {
	// The policy ID.
	PolicyID string `pathParam:"style=simple,explode=false,name=policyID"`
}

func (d *DeletePolicyRequest) GetPolicyID() string {
	if d == nil {
		return ""
	}
	return d.PolicyID
}

type DeletePolicyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (d DeletePolicyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeletePolicyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeletePolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeletePolicyResponse) GetErrorResponse() *components.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
