// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type DeleteRuleRequest struct {
	// The rule ID.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleID"`
}

func (d *DeleteRuleRequest) GetRuleID() string {
	if d == nil {
		return ""
	}
	return d.RuleID
}

type DeleteRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (d DeleteRuleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteRuleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteRuleResponse) GetErrorResponse() *components.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
