// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type EvaluateRuleRequest struct {
	// The rule ID.
	RuleID string                          `pathParam:"style=simple,explode=false,name=ruleID"`
	Body   *components.EvaluateRuleRequest `request:"mediaType=application/json"`
}

func (e EvaluateRuleRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluateRuleRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluateRuleRequest) GetRuleID() string {
	if e == nil {
		return ""
	}
	return e.RuleID
}

func (e *EvaluateRuleRequest) GetBody() *components.EvaluateRuleRequest {
	if e == nil {
		return nil
	}
	return e.Body
}

type EvaluateRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	EvaluationResponse *components.EvaluationResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (e EvaluateRuleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EvaluateRuleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EvaluateRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EvaluateRuleResponse) GetEvaluationResponse() *components.EvaluationResponse {
	if e == nil {
		return nil
	}
	return e.EvaluationResponse
}

func (e *EvaluateRuleResponse) GetErrorResponse() *components.ErrorResponse {
	if e == nil {
		return nil
	}
	return e.ErrorResponse
}
