// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type GetEvaluationRequest struct {
	// The evaluation ID.
	EvaluationID string `pathParam:"style=simple,explode=false,name=evaluationID"`
}

func (g *GetEvaluationRequest) GetEvaluationID() string {
	if g == nil {
		return ""
	}
	return g.EvaluationID
}

type GetEvaluationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	EvaluationResponse *components.EvaluationResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (g GetEvaluationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEvaluationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEvaluationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEvaluationResponse) GetEvaluationResponse() *components.EvaluationResponse {
	if g == nil {
		return nil
	}
	return g.EvaluationResponse
}

func (g *GetEvaluationResponse) GetErrorResponse() *components.ErrorResponse {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
