// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type GetPolicyRequest struct {
	// The policy ID.
	PolicyID string `pathParam:"style=simple,explode=false,name=policyID"`
}

func (g *GetPolicyRequest) GetPolicyID() string {
	if g == nil {
		return ""
	}
	return g.PolicyID
}

type GetPolicyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PolicyResponse *components.PolicyResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (g GetPolicyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPolicyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPolicyResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPolicyResponse) GetPolicyResponse() *components.PolicyResponse {
	if g == nil {
		return nil
	}
	return g.PolicyResponse
}

func (g *GetPolicyResponse) GetErrorResponse() *components.ErrorResponse {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
