// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type GetReconciliationRequest struct {
	// The reconciliation ID.
	ReconciliationID string `pathParam:"style=simple,explode=false,name=reconciliationID"`
}

func (g *GetReconciliationRequest) GetReconciliationID() string {
	if g == nil {
		return ""
	}
	return g.ReconciliationID
}

type GetReconciliationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ReconciliationResponse *components.ReconciliationResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (g GetReconciliationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetReconciliationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetReconciliationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetReconciliationResponse) GetReconciliationResponse() *components.ReconciliationResponse {
	if g == nil {
		return nil
	}
	return g.ReconciliationResponse
}

func (g *GetReconciliationResponse) GetErrorResponse() *components.ErrorResponse {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
