// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type GetRuleRequest struct {
	// The rule ID.
	RuleID string `pathParam:"style=simple,explode=false,name=ruleID"`
}

func (g *GetRuleRequest) GetRuleID() string {
	if g == nil {
		return ""
	}
	return g.RuleID
}

type GetRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RuleResponse *components.RuleResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (g GetRuleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRuleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRuleResponse) GetRuleResponse() *components.RuleResponse {
	if g == nil {
		return nil
	}
	return g.RuleResponse
}

func (g *GetRuleResponse) GetErrorResponse() *components.ErrorResponse {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
