// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type ListAlertEventsRequest struct {
	// The alert ID.
	AlertID string `pathParam:"style=simple,explode=false,name=alertID"`
	// The maximum number of results to return per page.
	//
	PageSize *int64 `queryParam:"style=form,explode=true,name=pageSize"`
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l *ListAlertEventsRequest) GetAlertID() string {
	if l == nil {
		return ""
	}
	return l.AlertID
}

func (l *ListAlertEventsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListAlertEventsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

type ListAlertEventsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AlertEventsCursorResponse *components.AlertEventsCursorResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (l ListAlertEventsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAlertEventsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAlertEventsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAlertEventsResponse) GetAlertEventsCursorResponse() *components.AlertEventsCursorResponse {
	if l == nil {
		return nil
	}
	return l.AlertEventsCursorResponse
}

func (l *ListAlertEventsResponse) GetErrorResponse() *components.ErrorResponse {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
