// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type ListPoliciesRequest struct {
	// The maximum number of results to return per page.
	//
	PageSize *int64 `queryParam:"style=form,explode=true,name=pageSize"`
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// JSON-encoded QueryBuilder filter. Omit it on cursor continuation requests.
	Query *string `queryParam:"style=form,explode=true,name=query"`
}

func (l *ListPoliciesRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListPoliciesRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListPoliciesRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

type ListPoliciesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	PoliciesCursorResponse *components.PoliciesCursorResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (l ListPoliciesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPoliciesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPoliciesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListPoliciesResponse) GetPoliciesCursorResponse() *components.PoliciesCursorResponse {
	if l == nil {
		return nil
	}
	return l.PoliciesCursorResponse
}

func (l *ListPoliciesResponse) GetErrorResponse() *components.ErrorResponse {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
