// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type PatchRuleRequest struct {
	// The rule ID.
	RuleID string                      `pathParam:"style=simple,explode=false,name=ruleID"`
	Body   components.RulePatchRequest `request:"mediaType=application/json"`
}

func (p *PatchRuleRequest) GetRuleID() string {
	if p == nil {
		return ""
	}
	return p.RuleID
}

func (p *PatchRuleRequest) GetBody() components.RulePatchRequest {
	if p == nil {
		return components.RulePatchRequest{}
	}
	return p.Body
}

type PatchRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RuleResponse *components.RuleResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (p PatchRuleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchRuleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatchRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PatchRuleResponse) GetRuleResponse() *components.RuleResponse {
	if p == nil {
		return nil
	}
	return p.RuleResponse
}

func (p *PatchRuleResponse) GetErrorResponse() *components.ErrorResponse {
	if p == nil {
		return nil
	}
	return p.ErrorResponse
}
