// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type ReconcileRequest struct {
	// The policy ID.
	PolicyID string                           `pathParam:"style=simple,explode=false,name=policyID"`
	Body     components.ReconciliationRequest `request:"mediaType=application/json"`
}

func (r *ReconcileRequest) GetPolicyID() string {
	if r == nil {
		return ""
	}
	return r.PolicyID
}

func (r *ReconcileRequest) GetBody() components.ReconciliationRequest {
	if r == nil {
		return components.ReconciliationRequest{}
	}
	return r.Body
}

type ReconcileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ReconciliationResponse *components.ReconciliationResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (r ReconcileResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReconcileResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReconcileResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReconcileResponse) GetReconciliationResponse() *components.ReconciliationResponse {
	if r == nil {
		return nil
	}
	return r.ReconciliationResponse
}

func (r *ReconcileResponse) GetErrorResponse() *components.ErrorResponse {
	if r == nil {
		return nil
	}
	return r.ErrorResponse
}
