// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type ResolveAlertRequest struct {
	// The alert ID.
	AlertID string                         `pathParam:"style=simple,explode=false,name=alertID"`
	Body    components.ResolveAlertRequest `request:"mediaType=application/json"`
}

func (r *ResolveAlertRequest) GetAlertID() string {
	if r == nil {
		return ""
	}
	return r.AlertID
}

func (r *ResolveAlertRequest) GetBody() components.ResolveAlertRequest {
	if r == nil {
		return components.ResolveAlertRequest{}
	}
	return r.Body
}

type ResolveAlertResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AlertResponse *components.AlertResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (r ResolveAlertResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResolveAlertResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResolveAlertResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ResolveAlertResponse) GetAlertResponse() *components.AlertResponse {
	if r == nil {
		return nil
	}
	return r.AlertResponse
}

func (r *ResolveAlertResponse) GetErrorResponse() *components.ErrorResponse {
	if r == nil {
		return nil
	}
	return r.ErrorResponse
}
