// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type SnoozeAlertRequest struct {
	// The alert ID.
	AlertID string                        `pathParam:"style=simple,explode=false,name=alertID"`
	Body    components.SnoozeAlertRequest `request:"mediaType=application/json"`
}

func (s *SnoozeAlertRequest) GetAlertID() string {
	if s == nil {
		return ""
	}
	return s.AlertID
}

func (s *SnoozeAlertRequest) GetBody() components.SnoozeAlertRequest {
	if s == nil {
		return components.SnoozeAlertRequest{}
	}
	return s.Body
}

type SnoozeAlertResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AlertResponse *components.AlertResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (s SnoozeAlertResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SnoozeAlertResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SnoozeAlertResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SnoozeAlertResponse) GetAlertResponse() *components.AlertResponse {
	if s == nil {
		return nil
	}
	return s.AlertResponse
}

func (s *SnoozeAlertResponse) GetErrorResponse() *components.ErrorResponse {
	if s == nil {
		return nil
	}
	return s.ErrorResponse
}
