// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/models/components"
)

type UnsnoozeAlertRequest struct {
	// The alert ID.
	AlertID string                          `pathParam:"style=simple,explode=false,name=alertID"`
	Body    components.UnsnoozeAlertRequest `request:"mediaType=application/json"`
}

func (u *UnsnoozeAlertRequest) GetAlertID() string {
	if u == nil {
		return ""
	}
	return u.AlertID
}

func (u *UnsnoozeAlertRequest) GetBody() components.UnsnoozeAlertRequest {
	if u == nil {
		return components.UnsnoozeAlertRequest{}
	}
	return u.Body
}

type UnsnoozeAlertResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AlertResponse *components.AlertResponse
	// Error response
	ErrorResponse *components.ErrorResponse
}

func (u UnsnoozeAlertResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnsnoozeAlertResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UnsnoozeAlertResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UnsnoozeAlertResponse) GetAlertResponse() *components.AlertResponse {
	if u == nil {
		return nil
	}
	return u.AlertResponse
}

func (u *UnsnoozeAlertResponse) GetErrorResponse() *components.ErrorResponse {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}
