// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source store.go -destination store_generated.go -package ledgerstore . ledgerClient
//

// Package ledgerstore is a generated GoMock package.
package ledgerstore

import (
	context "context"
	reflect "reflect"

	ledger "github.com/formancehq/reconciliation/internal/ledger"
	commonpb "github.com/formancehq/reconciliation/internal/ledgerpb/commonpb"
	gomock "go.uber.org/mock/gomock"
)

// MockledgerClient is a mock of ledgerClient interface.
type MockledgerClient struct {
	ctrl     *gomock.Controller
	recorder *MockledgerClientMockRecorder
	isgomock struct{}
}

// MockledgerClientMockRecorder is the mock recorder for MockledgerClient.
type MockledgerClientMockRecorder struct {
	mock *MockledgerClient
}

// NewMockledgerClient creates a new mock instance.
func NewMockledgerClient(ctrl *gomock.Controller) *MockledgerClient {
	mock := &MockledgerClient{ctrl: ctrl}
	mock.recorder = &MockledgerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockledgerClient) EXPECT() *MockledgerClientMockRecorder {
	return m.recorder
}

// ApplyMetadata mocks base method.
func (m *MockledgerClient) ApplyMetadata(ctx context.Context, ledgerName, address string, set map[string]*commonpb.MetadataValue, deleteKeys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ledgerName, address, set}
	for _, a := range deleteKeys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ApplyMetadata", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyMetadata indicates an expected call of ApplyMetadata.
func (mr *MockledgerClientMockRecorder) ApplyMetadata(ctx, ledgerName, address, set any, deleteKeys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ledgerName, address, set}, deleteKeys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMetadata", reflect.TypeOf((*MockledgerClient)(nil).ApplyMetadata), varargs...)
}

// CreateTransaction mocks base method.
func (m *MockledgerClient) CreateTransaction(ctx context.Context, in ledger.CreateTransactionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockledgerClientMockRecorder) CreateTransaction(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockledgerClient)(nil).CreateTransaction), ctx, in)
}

// DeleteAccountMetadata mocks base method.
func (m *MockledgerClient) DeleteAccountMetadata(ctx context.Context, ledgerName, address string, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ledgerName, address}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAccountMetadata", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccountMetadata indicates an expected call of DeleteAccountMetadata.
func (mr *MockledgerClientMockRecorder) DeleteAccountMetadata(ctx, ledgerName, address any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ledgerName, address}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountMetadata", reflect.TypeOf((*MockledgerClient)(nil).DeleteAccountMetadata), varargs...)
}

// GetAccount mocks base method.
func (m *MockledgerClient) GetAccount(ctx context.Context, ledgerName, address string) (*commonpb.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, ledgerName, address)
	ret0, _ := ret[0].(*commonpb.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockledgerClientMockRecorder) GetAccount(ctx, ledgerName, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockledgerClient)(nil).GetAccount), ctx, ledgerName, address)
}

// QueryAccounts mocks base method.
func (m *MockledgerClient) QueryAccounts(ctx context.Context, ledgerName string, filter *commonpb.QueryFilter) ([]*commonpb.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAccounts", ctx, ledgerName, filter)
	ret0, _ := ret[0].([]*commonpb.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAccounts indicates an expected call of QueryAccounts.
func (mr *MockledgerClientMockRecorder) QueryAccounts(ctx, ledgerName, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAccounts", reflect.TypeOf((*MockledgerClient)(nil).QueryAccounts), ctx, ledgerName, filter)
}

// SaveAccountMetadataValues mocks base method.
func (m *MockledgerClient) SaveAccountMetadataValues(ctx context.Context, ledgerName, address string, md map[string]*commonpb.MetadataValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAccountMetadataValues", ctx, ledgerName, address, md)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAccountMetadataValues indicates an expected call of SaveAccountMetadataValues.
func (mr *MockledgerClientMockRecorder) SaveAccountMetadataValues(ctx, ledgerName, address, md any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAccountMetadataValues", reflect.TypeOf((*MockledgerClient)(nil).SaveAccountMetadataValues), ctx, ledgerName, address, md)
}
