package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const expectedUnmarshalCalls = 18

const losslessHelper = `// Code generated by internal/generateclient. DO NOT EDIT.

package utils

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

// unmarshalJSONLossless gives arbitrary JSON values json.Number leaves instead
// of float64 leaves, preserving integer and decimal tokens during round trips.
func unmarshalJSONLossless(data []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := decoder.Decode(destination); err != nil {
		return err
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		if err == nil {
			return fmt.Errorf("multiple JSON values")
		}
		return err
	}
	return nil
}
`

func main() {
	clientRoot := flag.String("client", "pkg/client", "generated client directory")
	flag.Parse()

	jsonPath := filepath.Join(*clientRoot, "internal", "utils", "json.go")
	contents, err := os.ReadFile(jsonPath)
	if err != nil {
		fatal(err)
	}
	plainCount := strings.Count(string(contents), "json.Unmarshal(")
	losslessCount := strings.Count(string(contents), "unmarshalJSONLossless(")
	switch {
	case plainCount == expectedUnmarshalCalls:
		contents = bytes.ReplaceAll(contents, []byte("json.Unmarshal("), []byte("unmarshalJSONLossless("))
	case plainCount == 0 && losslessCount == expectedUnmarshalCalls:
		// Speakeasy persistent edits already restored the deterministic patch.
	default:
		fatal(fmt.Errorf("generated JSON decoder shape drifted: json.Unmarshal=%d lossless=%d, want %d calls", plainCount, losslessCount, expectedUnmarshalCalls))
	}
	if err := os.WriteFile(jsonPath, contents, 0o644); err != nil {
		fatal(err)
	}
	helperPath := filepath.Join(*clientRoot, "internal", "utils", "lossless_json.go")
	if err := os.WriteFile(helperPath, []byte(losslessHelper), 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generateclient:", err)
	os.Exit(1)
}
