// Code generated by MockGen. DO NOT EDIT.
// Source: provisioner.go
//
// Generated by this command:
//
//	mockgen -source provisioner.go -destination provisioner_generated.go -package ledger . provisionAPI
//

// Package ledger is a generated GoMock package.
package ledger

import (
	context "context"
	reflect "reflect"

	commonpb "github.com/formancehq/reconciliation/internal/ledgerpb/commonpb"
	servicepb "github.com/formancehq/reconciliation/internal/ledgerpb/servicepb"
	gomock "go.uber.org/mock/gomock"
)

// MockprovisionAPI is a mock of provisionAPI interface.
type MockprovisionAPI struct {
	ctrl     *gomock.Controller
	recorder *MockprovisionAPIMockRecorder
	isgomock struct{}
}

// MockprovisionAPIMockRecorder is the mock recorder for MockprovisionAPI.
type MockprovisionAPIMockRecorder struct {
	mock *MockprovisionAPI
}

// NewMockprovisionAPI creates a new mock instance.
func NewMockprovisionAPI(ctrl *gomock.Controller) *MockprovisionAPI {
	mock := &MockprovisionAPI{ctrl: ctrl}
	mock.recorder = &MockprovisionAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprovisionAPI) EXPECT() *MockprovisionAPIMockRecorder {
	return m.recorder
}

// CreateIndex mocks base method.
func (m *MockprovisionAPI) CreateIndex(ctx context.Context, ledger string, index *servicepb.CreateIndexRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex", ctx, ledger, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockprovisionAPIMockRecorder) CreateIndex(ctx, ledger, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockprovisionAPI)(nil).CreateIndex), ctx, ledger, index)
}

// CreateLedger mocks base method.
func (m *MockprovisionAPI) CreateLedger(ctx context.Context, name string, schema []*commonpb.SetMetadataFieldTypeCommand, accountTypes map[string]*commonpb.AccountType, enforcement commonpb.ChartEnforcementMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLedger", ctx, name, schema, accountTypes, enforcement)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLedger indicates an expected call of CreateLedger.
func (mr *MockprovisionAPIMockRecorder) CreateLedger(ctx, name, schema, accountTypes, enforcement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLedger", reflect.TypeOf((*MockprovisionAPI)(nil).CreateLedger), ctx, name, schema, accountTypes, enforcement)
}

// CreatePreparedQuery mocks base method.
func (m *MockprovisionAPI) CreatePreparedQuery(ctx context.Context, ledger string, query *commonpb.PreparedQuery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePreparedQuery", ctx, ledger, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePreparedQuery indicates an expected call of CreatePreparedQuery.
func (mr *MockprovisionAPIMockRecorder) CreatePreparedQuery(ctx, ledger, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePreparedQuery", reflect.TypeOf((*MockprovisionAPI)(nil).CreatePreparedQuery), ctx, ledger, query)
}

// SaveNumscript mocks base method.
func (m *MockprovisionAPI) SaveNumscript(ctx context.Context, ledger, name, content, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNumscript", ctx, ledger, name, content, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNumscript indicates an expected call of SaveNumscript.
func (mr *MockprovisionAPIMockRecorder) SaveNumscript(ctx, ledger, name, content, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNumscript", reflect.TypeOf((*MockprovisionAPI)(nil).SaveNumscript), ctx, ledger, name, content, version)
}
