// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source backend.go -destination backend_generated.go -package backend . Service
//

// Package backend is a generated GoMock package.
package backend

import (
	context "context"
	reflect "reflect"

	bunpaginate "github.com/formancehq/go-libs/bun/bunpaginate"
	service "github.com/formancehq/reconciliation/internal/api/service"
	models "github.com/formancehq/reconciliation/internal/models"
	storage "github.com/formancehq/reconciliation/internal/storage"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AcceptAlert mocks base method.
func (m *MockService) AcceptAlert(ctx context.Context, id uuid.UUID, req *service.AcceptAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptAlert indicates an expected call of AcceptAlert.
func (mr *MockServiceMockRecorder) AcceptAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptAlert", reflect.TypeOf((*MockService)(nil).AcceptAlert), ctx, id, req)
}

// AckAlert mocks base method.
func (m *MockService) AckAlert(ctx context.Context, id uuid.UUID, req *service.AckAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AckAlert indicates an expected call of AckAlert.
func (mr *MockServiceMockRecorder) AckAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckAlert", reflect.TypeOf((*MockService)(nil).AckAlert), ctx, id, req)
}

// CreatePolicy mocks base method.
func (m *MockService) CreatePolicy(ctx context.Context, req *service.CreatePolicyRequest) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicy", ctx, req)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicy indicates an expected call of CreatePolicy.
func (mr *MockServiceMockRecorder) CreatePolicy(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicy", reflect.TypeOf((*MockService)(nil).CreatePolicy), ctx, req)
}

// CreateRule mocks base method.
func (m *MockService) CreateRule(ctx context.Context, req *service.CreateRuleRequest) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, req)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockServiceMockRecorder) CreateRule(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockService)(nil).CreateRule), ctx, req)
}

// DeletePolicy mocks base method.
func (m *MockService) DeletePolicy(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicy", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockServiceMockRecorder) DeletePolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockService)(nil).DeletePolicy), ctx, id)
}

// DeleteRule mocks base method.
func (m *MockService) DeleteRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockServiceMockRecorder) DeleteRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockService)(nil).DeleteRule), ctx, id)
}

// EvaluateRule mocks base method.
func (m *MockService) EvaluateRule(ctx context.Context, id uuid.UUID, req service.EvaluateRuleRequest) (*models.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateRule", ctx, id, req)
	ret0, _ := ret[0].(*models.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateRule indicates an expected call of EvaluateRule.
func (mr *MockServiceMockRecorder) EvaluateRule(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateRule", reflect.TypeOf((*MockService)(nil).EvaluateRule), ctx, id, req)
}

// GetAlert mocks base method.
func (m *MockService) GetAlert(ctx context.Context, id uuid.UUID) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlert", ctx, id)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlert indicates an expected call of GetAlert.
func (mr *MockServiceMockRecorder) GetAlert(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlert", reflect.TypeOf((*MockService)(nil).GetAlert), ctx, id)
}

// GetEvaluation mocks base method.
func (m *MockService) GetEvaluation(ctx context.Context, id uuid.UUID) (*models.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluation", ctx, id)
	ret0, _ := ret[0].(*models.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluation indicates an expected call of GetEvaluation.
func (mr *MockServiceMockRecorder) GetEvaluation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluation", reflect.TypeOf((*MockService)(nil).GetEvaluation), ctx, id)
}

// GetPolicy mocks base method.
func (m *MockService) GetPolicy(ctx context.Context, id string) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, id)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockServiceMockRecorder) GetPolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockService)(nil).GetPolicy), ctx, id)
}

// GetReconciliation mocks base method.
func (m *MockService) GetReconciliation(ctx context.Context, id string) (*models.Reconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReconciliation", ctx, id)
	ret0, _ := ret[0].(*models.Reconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReconciliation indicates an expected call of GetReconciliation.
func (mr *MockServiceMockRecorder) GetReconciliation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReconciliation", reflect.TypeOf((*MockService)(nil).GetReconciliation), ctx, id)
}

// GetRule mocks base method.
func (m *MockService) GetRule(ctx context.Context, id uuid.UUID) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockServiceMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockService)(nil).GetRule), ctx, id)
}

// ListAlertEvents mocks base method.
func (m *MockService) ListAlertEvents(ctx context.Context, alertID uuid.UUID) ([]models.AlertEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlertEvents", ctx, alertID)
	ret0, _ := ret[0].([]models.AlertEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlertEvents indicates an expected call of ListAlertEvents.
func (mr *MockServiceMockRecorder) ListAlertEvents(ctx, alertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlertEvents", reflect.TypeOf((*MockService)(nil).ListAlertEvents), ctx, alertID)
}

// ListAlerts mocks base method.
func (m *MockService) ListAlerts(ctx context.Context, q storage.GetAlertsQuery) (*bunpaginate.Cursor[models.Alert], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlerts", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Alert])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlerts indicates an expected call of ListAlerts.
func (mr *MockServiceMockRecorder) ListAlerts(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlerts", reflect.TypeOf((*MockService)(nil).ListAlerts), ctx, q)
}

// ListEvaluations mocks base method.
func (m *MockService) ListEvaluations(ctx context.Context, q storage.GetEvaluationsQuery) (*bunpaginate.Cursor[models.Evaluation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvaluations", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Evaluation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvaluations indicates an expected call of ListEvaluations.
func (mr *MockServiceMockRecorder) ListEvaluations(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvaluations", reflect.TypeOf((*MockService)(nil).ListEvaluations), ctx, q)
}

// ListPolicies mocks base method.
func (m *MockService) ListPolicies(ctx context.Context, q storage.GetPoliciesQuery) (*bunpaginate.Cursor[models.Policy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Policy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockServiceMockRecorder) ListPolicies(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockService)(nil).ListPolicies), ctx, q)
}

// ListReconciliations mocks base method.
func (m *MockService) ListReconciliations(ctx context.Context, q storage.GetReconciliationsQuery) (*bunpaginate.Cursor[models.Reconciliation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReconciliations", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Reconciliation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReconciliations indicates an expected call of ListReconciliations.
func (mr *MockServiceMockRecorder) ListReconciliations(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReconciliations", reflect.TypeOf((*MockService)(nil).ListReconciliations), ctx, q)
}

// ListRules mocks base method.
func (m *MockService) ListRules(ctx context.Context, q storage.GetRulesQuery) (*bunpaginate.Cursor[models.Rule], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Rule])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockServiceMockRecorder) ListRules(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockService)(nil).ListRules), ctx, q)
}

// PatchRule mocks base method.
func (m *MockService) PatchRule(ctx context.Context, id uuid.UUID, patch storage.RulePatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchRule", ctx, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchRule indicates an expected call of PatchRule.
func (mr *MockServiceMockRecorder) PatchRule(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchRule", reflect.TypeOf((*MockService)(nil).PatchRule), ctx, id, patch)
}

// Reconciliation mocks base method.
func (m *MockService) Reconciliation(ctx context.Context, policyID string, req *service.ReconciliationRequest) (*models.Reconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconciliation", ctx, policyID, req)
	ret0, _ := ret[0].(*models.Reconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconciliation indicates an expected call of Reconciliation.
func (mr *MockServiceMockRecorder) Reconciliation(ctx, policyID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconciliation", reflect.TypeOf((*MockService)(nil).Reconciliation), ctx, policyID, req)
}

// ResolveAlert mocks base method.
func (m *MockService) ResolveAlert(ctx context.Context, id uuid.UUID, req *service.ResolveAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAlert indicates an expected call of ResolveAlert.
func (mr *MockServiceMockRecorder) ResolveAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAlert", reflect.TypeOf((*MockService)(nil).ResolveAlert), ctx, id, req)
}

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// GetService mocks base method.
func (m *MockBackend) GetService() Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService")
	ret0, _ := ret[0].(Service)
	return ret0
}

// GetService indicates an expected call of GetService.
func (mr *MockBackendMockRecorder) GetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockBackend)(nil).GetService))
}
