// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source backend.go -destination backend_generated.go -package backend . Service
//

// Package backend is a generated GoMock package.
package backend

import (
	context "context"
	reflect "reflect"

	bunpaginate "github.com/formancehq/go-libs/bun/bunpaginate"
	service "github.com/formancehq/reconciliation/internal/api/service"
	models "github.com/formancehq/reconciliation/internal/models"
	store "github.com/formancehq/reconciliation/internal/store"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AcceptAlert mocks base method.
func (m *MockService) AcceptAlert(ctx context.Context, id uuid.UUID, req *service.AcceptAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptAlert indicates an expected call of AcceptAlert.
func (mr *MockServiceMockRecorder) AcceptAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptAlert", reflect.TypeOf((*MockService)(nil).AcceptAlert), ctx, id, req)
}

// AckAlert mocks base method.
func (m *MockService) AckAlert(ctx context.Context, id uuid.UUID, req *service.AckAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AckAlert indicates an expected call of AckAlert.
func (mr *MockServiceMockRecorder) AckAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckAlert", reflect.TypeOf((*MockService)(nil).AckAlert), ctx, id, req)
}

// CreateRule mocks base method.
func (m *MockService) CreateRule(ctx context.Context, req *service.CreateRuleRequest) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, req)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockServiceMockRecorder) CreateRule(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockService)(nil).CreateRule), ctx, req)
}

// DeleteRule mocks base method.
func (m *MockService) DeleteRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockServiceMockRecorder) DeleteRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockService)(nil).DeleteRule), ctx, id)
}

// EvaluateRule mocks base method.
func (m *MockService) EvaluateRule(ctx context.Context, id uuid.UUID, req service.EvaluateRuleRequest) (*models.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateRule", ctx, id, req)
	ret0, _ := ret[0].(*models.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateRule indicates an expected call of EvaluateRule.
func (mr *MockServiceMockRecorder) EvaluateRule(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateRule", reflect.TypeOf((*MockService)(nil).EvaluateRule), ctx, id, req)
}

// GetAlert mocks base method.
func (m *MockService) GetAlert(ctx context.Context, id uuid.UUID) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlert", ctx, id)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlert indicates an expected call of GetAlert.
func (mr *MockServiceMockRecorder) GetAlert(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlert", reflect.TypeOf((*MockService)(nil).GetAlert), ctx, id)
}

// GetRule mocks base method.
func (m *MockService) GetRule(ctx context.Context, id uuid.UUID) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockServiceMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockService)(nil).GetRule), ctx, id)
}

// ListAlertEvents mocks base method.
func (m *MockService) ListAlertEvents(ctx context.Context, alertID uuid.UUID, q store.GetAlertEventsQuery) (*bunpaginate.Cursor[models.AlertEvent], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlertEvents", ctx, alertID, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.AlertEvent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlertEvents indicates an expected call of ListAlertEvents.
func (mr *MockServiceMockRecorder) ListAlertEvents(ctx, alertID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlertEvents", reflect.TypeOf((*MockService)(nil).ListAlertEvents), ctx, alertID, q)
}

// ListAlerts mocks base method.
func (m *MockService) ListAlerts(ctx context.Context, q store.GetAlertsQuery) (*bunpaginate.Cursor[models.Alert], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAlerts", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Alert])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAlerts indicates an expected call of ListAlerts.
func (mr *MockServiceMockRecorder) ListAlerts(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAlerts", reflect.TypeOf((*MockService)(nil).ListAlerts), ctx, q)
}

// ListCaptures mocks base method.
func (m *MockService) ListCaptures(ctx context.Context, ruleID uuid.UUID, q store.GetCapturesQuery) (*bunpaginate.Cursor[models.Capture], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCaptures", ctx, ruleID, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Capture])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCaptures indicates an expected call of ListCaptures.
func (mr *MockServiceMockRecorder) ListCaptures(ctx, ruleID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCaptures", reflect.TypeOf((*MockService)(nil).ListCaptures), ctx, ruleID, q)
}

// ListRuleActivities mocks base method.
func (m *MockService) ListRuleActivities(ctx context.Context, ruleID uuid.UUID, q store.GetRuleActivitiesQuery) (*bunpaginate.Cursor[models.RuleActivity], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRuleActivities", ctx, ruleID, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.RuleActivity])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRuleActivities indicates an expected call of ListRuleActivities.
func (mr *MockServiceMockRecorder) ListRuleActivities(ctx, ruleID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRuleActivities", reflect.TypeOf((*MockService)(nil).ListRuleActivities), ctx, ruleID, q)
}

// ListRules mocks base method.
func (m *MockService) ListRules(ctx context.Context, q store.GetRulesQuery) (*bunpaginate.Cursor[models.Rule], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Rule])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockServiceMockRecorder) ListRules(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockService)(nil).ListRules), ctx, q)
}

// PatchRule mocks base method.
func (m *MockService) PatchRule(ctx context.Context, id uuid.UUID, patch store.RulePatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchRule", ctx, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchRule indicates an expected call of PatchRule.
func (mr *MockServiceMockRecorder) PatchRule(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchRule", reflect.TypeOf((*MockService)(nil).PatchRule), ctx, id, patch)
}

// ResolveAlert mocks base method.
func (m *MockService) ResolveAlert(ctx context.Context, id uuid.UUID, req *service.ResolveAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAlert indicates an expected call of ResolveAlert.
func (mr *MockServiceMockRecorder) ResolveAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAlert", reflect.TypeOf((*MockService)(nil).ResolveAlert), ctx, id, req)
}

// SnoozeAlert mocks base method.
func (m *MockService) SnoozeAlert(ctx context.Context, id uuid.UUID, req *service.SnoozeAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnoozeAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnoozeAlert indicates an expected call of SnoozeAlert.
func (mr *MockServiceMockRecorder) SnoozeAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnoozeAlert", reflect.TypeOf((*MockService)(nil).SnoozeAlert), ctx, id, req)
}

// UnsnoozeAlert mocks base method.
func (m *MockService) UnsnoozeAlert(ctx context.Context, id uuid.UUID, req *service.UnsnoozeAlertRequest) (*models.Alert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsnoozeAlert", ctx, id, req)
	ret0, _ := ret[0].(*models.Alert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsnoozeAlert indicates an expected call of UnsnoozeAlert.
func (mr *MockServiceMockRecorder) UnsnoozeAlert(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsnoozeAlert", reflect.TypeOf((*MockService)(nil).UnsnoozeAlert), ctx, id, req)
}

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// GetService mocks base method.
func (m *MockBackend) GetService() Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService")
	ret0, _ := ret[0].(Service)
	return ret0
}

// GetService indicates an expected call of GetService.
func (mr *MockBackendMockRecorder) GetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockBackend)(nil).GetService))
}
