// Code generated by MockGen. DO NOT EDIT.
// Source: backend.go
//
// Generated by this command:
//
//	mockgen -source backend.go -destination backend_generated.go -package backend . Service
//

// Package backend is a generated GoMock package.
package backend

import (
	context "context"
	reflect "reflect"

	bunpaginate "github.com/formancehq/go-libs/bun/bunpaginate"
	service "github.com/formancehq/reconciliation/internal/api/service"
	models "github.com/formancehq/reconciliation/internal/models"
	storage "github.com/formancehq/reconciliation/internal/storage"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AcceptIncident mocks base method.
func (m *MockService) AcceptIncident(ctx context.Context, id uuid.UUID, req *service.AcceptIncidentRequest) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptIncident", ctx, id, req)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptIncident indicates an expected call of AcceptIncident.
func (mr *MockServiceMockRecorder) AcceptIncident(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptIncident", reflect.TypeOf((*MockService)(nil).AcceptIncident), ctx, id, req)
}

// AckIncident mocks base method.
func (m *MockService) AckIncident(ctx context.Context, id uuid.UUID, req *service.AckIncidentRequest) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckIncident", ctx, id, req)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AckIncident indicates an expected call of AckIncident.
func (mr *MockServiceMockRecorder) AckIncident(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckIncident", reflect.TypeOf((*MockService)(nil).AckIncident), ctx, id, req)
}

// CreatePolicy mocks base method.
func (m *MockService) CreatePolicy(ctx context.Context, req *service.CreatePolicyRequest) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicy", ctx, req)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicy indicates an expected call of CreatePolicy.
func (mr *MockServiceMockRecorder) CreatePolicy(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicy", reflect.TypeOf((*MockService)(nil).CreatePolicy), ctx, req)
}

// CreateRule mocks base method.
func (m *MockService) CreateRule(ctx context.Context, req *service.CreateRuleRequest) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, req)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockServiceMockRecorder) CreateRule(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockService)(nil).CreateRule), ctx, req)
}

// DeletePolicy mocks base method.
func (m *MockService) DeletePolicy(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicy", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockServiceMockRecorder) DeletePolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockService)(nil).DeletePolicy), ctx, id)
}

// DeleteRule mocks base method.
func (m *MockService) DeleteRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockServiceMockRecorder) DeleteRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockService)(nil).DeleteRule), ctx, id)
}

// EvaluateRule mocks base method.
func (m *MockService) EvaluateRule(ctx context.Context, id uuid.UUID, req service.EvaluateRuleRequest) (*models.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateRule", ctx, id, req)
	ret0, _ := ret[0].(*models.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateRule indicates an expected call of EvaluateRule.
func (mr *MockServiceMockRecorder) EvaluateRule(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateRule", reflect.TypeOf((*MockService)(nil).EvaluateRule), ctx, id, req)
}

// GetEvaluation mocks base method.
func (m *MockService) GetEvaluation(ctx context.Context, id uuid.UUID) (*models.Evaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluation", ctx, id)
	ret0, _ := ret[0].(*models.Evaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluation indicates an expected call of GetEvaluation.
func (mr *MockServiceMockRecorder) GetEvaluation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluation", reflect.TypeOf((*MockService)(nil).GetEvaluation), ctx, id)
}

// GetIncident mocks base method.
func (m *MockService) GetIncident(ctx context.Context, id uuid.UUID) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncident", ctx, id)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncident indicates an expected call of GetIncident.
func (mr *MockServiceMockRecorder) GetIncident(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncident", reflect.TypeOf((*MockService)(nil).GetIncident), ctx, id)
}

// GetPolicy mocks base method.
func (m *MockService) GetPolicy(ctx context.Context, id string) (*models.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, id)
	ret0, _ := ret[0].(*models.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockServiceMockRecorder) GetPolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockService)(nil).GetPolicy), ctx, id)
}

// GetReconciliation mocks base method.
func (m *MockService) GetReconciliation(ctx context.Context, id string) (*models.Reconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReconciliation", ctx, id)
	ret0, _ := ret[0].(*models.Reconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReconciliation indicates an expected call of GetReconciliation.
func (mr *MockServiceMockRecorder) GetReconciliation(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReconciliation", reflect.TypeOf((*MockService)(nil).GetReconciliation), ctx, id)
}

// GetRule mocks base method.
func (m *MockService) GetRule(ctx context.Context, id uuid.UUID) (*models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(*models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockServiceMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockService)(nil).GetRule), ctx, id)
}

// ListEvaluations mocks base method.
func (m *MockService) ListEvaluations(ctx context.Context, q storage.GetEvaluationsQuery) (*bunpaginate.Cursor[models.Evaluation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvaluations", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Evaluation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvaluations indicates an expected call of ListEvaluations.
func (mr *MockServiceMockRecorder) ListEvaluations(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvaluations", reflect.TypeOf((*MockService)(nil).ListEvaluations), ctx, q)
}

// ListIncidents mocks base method.
func (m *MockService) ListIncidents(ctx context.Context, q storage.GetIncidentsQuery) (*bunpaginate.Cursor[models.Incident], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidents", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Incident])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidents indicates an expected call of ListIncidents.
func (mr *MockServiceMockRecorder) ListIncidents(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidents", reflect.TypeOf((*MockService)(nil).ListIncidents), ctx, q)
}

// ListPolicies mocks base method.
func (m *MockService) ListPolicies(ctx context.Context, q storage.GetPoliciesQuery) (*bunpaginate.Cursor[models.Policy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Policy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockServiceMockRecorder) ListPolicies(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockService)(nil).ListPolicies), ctx, q)
}

// ListReconciliations mocks base method.
func (m *MockService) ListReconciliations(ctx context.Context, q storage.GetReconciliationsQuery) (*bunpaginate.Cursor[models.Reconciliation], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReconciliations", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Reconciliation])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReconciliations indicates an expected call of ListReconciliations.
func (mr *MockServiceMockRecorder) ListReconciliations(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReconciliations", reflect.TypeOf((*MockService)(nil).ListReconciliations), ctx, q)
}

// ListRules mocks base method.
func (m *MockService) ListRules(ctx context.Context, q storage.GetRulesQuery) (*bunpaginate.Cursor[models.Rule], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx, q)
	ret0, _ := ret[0].(*bunpaginate.Cursor[models.Rule])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockServiceMockRecorder) ListRules(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockService)(nil).ListRules), ctx, q)
}

// PatchRule mocks base method.
func (m *MockService) PatchRule(ctx context.Context, id uuid.UUID, patch storage.RulePatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchRule", ctx, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchRule indicates an expected call of PatchRule.
func (mr *MockServiceMockRecorder) PatchRule(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchRule", reflect.TypeOf((*MockService)(nil).PatchRule), ctx, id, patch)
}

// Reconciliation mocks base method.
func (m *MockService) Reconciliation(ctx context.Context, policyID string, req *service.ReconciliationRequest) (*models.Reconciliation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconciliation", ctx, policyID, req)
	ret0, _ := ret[0].(*models.Reconciliation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconciliation indicates an expected call of Reconciliation.
func (mr *MockServiceMockRecorder) Reconciliation(ctx, policyID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconciliation", reflect.TypeOf((*MockService)(nil).Reconciliation), ctx, policyID, req)
}

// ResolveIncident mocks base method.
func (m *MockService) ResolveIncident(ctx context.Context, id uuid.UUID, req *service.ResolveIncidentRequest) (*models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIncident", ctx, id, req)
	ret0, _ := ret[0].(*models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveIncident indicates an expected call of ResolveIncident.
func (mr *MockServiceMockRecorder) ResolveIncident(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIncident", reflect.TypeOf((*MockService)(nil).ResolveIncident), ctx, id, req)
}

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// GetService mocks base method.
func (m *MockBackend) GetService() Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService")
	ret0, _ := ret[0].(Service)
	return ret0
}

// GetService indicates an expected call of GetService.
func (mr *MockBackendMockRecorder) GetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockBackend)(nil).GetService))
}
