// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package client

// Generated from OpenAPI doc version RECONCILIATION_VERSION and generator version 2.879.6

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/config"
	"github.com/formancehq/reconciliation/pkg/client/internal/hooks"
	"github.com/formancehq/reconciliation/pkg/client/internal/utils"
	"github.com/formancehq/reconciliation/pkg/client/retry"
	"net/http"
	"time"
)

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

type Formance struct {
	SDKVersion     string
	Reconciliation *Reconciliation

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*Formance)

// WithServerURL allows providing an alternative server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *Formance) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *Formance) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *Formance) {
		sdk.sdkConfiguration.Client = client
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *Formance) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *Formance) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided serverURL and options
func New(serverURL string, opts ...SDKOption) *Formance {
	sdk := &Formance{
		SDKVersion: "0.1.0",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent: "speakeasy-sdk/go 0.1.0 2.879.6 RECONCILIATION_VERSION github.com/formancehq/reconciliation/pkg/client",
		},
		hooks: hooks.New(),
	}
	sdk.sdkConfiguration.ServerURL = serverURL

	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Reconciliation = newReconciliation(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
