// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package client

import (
	"github.com/formancehq/reconciliation/pkg/client/internal/config"
	"github.com/formancehq/reconciliation/pkg/client/internal/hooks"
)

type Reconciliation struct {
	V1 *V1

	rootSDK          *Formance
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newReconciliation(rootSDK *Formance, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Reconciliation {
	return &Reconciliation{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		V1:               newV1(rootSDK, sdkConfig, hooks),
	}
}
